import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const guard = resolve(root, 'scripts/exec-guard.mjs');
const sha = (bytes) => createHash('sha256').update(bytes).digest('hex');
const git = (cwd, args, env = process.env) => spawnSync('git', args, { cwd, env, encoding: 'utf8', shell: false });
const run = (cwd, mode, args = [], env = process.env) => spawnSync(process.execPath, [guard, mode, ...args], { cwd, env, encoding: 'utf8', shell: false });
const json = (r) => JSON.parse(r.stdout);

async function repoFixture({ space = false } = {}) {
  const base = await mkdtemp(join(tmpdir(), space ? 'exec guard space ' : 'exec-guard-'));
  const repo = join(base, 'repo with space'); const remote = join(base, 'remote.git');
  await mkdir(repo); git(base, ['init', '--bare', remote]); git(repo, ['init']); git(repo, ['config','user.name','Guard Test']); git(repo, ['config','user.email','guard@test.local']);
  await writeFile(join(repo,'base.txt'),'base\n'); git(repo,['add','base.txt']); git(repo,['commit','-m','base']); git(repo,['branch','-M','candidate/interpreter-adapter-v1-work']); git(repo,['remote','add','origin',remote]); git(repo,['push','-u','origin','candidate/interpreter-adapter-v1-work']); await mkdir(join(repo,'node_modules'));
  const head=git(repo,['rev-parse','HEAD']).stdout.trim();
  return { base, repo, remote, head, branch:'candidate/interpreter-adapter-v1-work', cleanup:()=>rm(base,{recursive:true,force:true}) };
}
const expected = (f) => ['--expected-head',f.head,'--expected-branch',f.branch,'--expected-remote',f.head,'--expected-ahead','0','--expected-behind','0','--require-node-modules'];

test('T1 clean preflight passes', async()=>{const f=await repoFixture();try{const r=run(f.repo,'preflight',expected(f));assert.equal(r.status,0,r.stderr);assert.equal(json(r).ok,true);}finally{await f.cleanup();}});
test('T2 dirty worktree causes named preflight failure',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'base.txt'),'dirty\n');const r=run(f.repo,'preflight',expected(f));assert.equal(r.status,1);assert.ok(json(r).failures.some(x=>x.startsWith('WORKTREE_DIRTY:')));}finally{await f.cleanup();}});
test('T3 staged content causes staging failure',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'base.txt'),'staged\n');git(f.repo,['add','base.txt']);const r=run(f.repo,'preflight',expected(f));assert.equal(r.status,1);assert.ok(json(r).failures.includes('STAGING_NOT_CLEAN'));}finally{await f.cleanup();}});
test('T4 nonignored untracked file causes exact failure',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'new.txt'),'x');const r=run(f.repo,'preflight',expected(f));assert.equal(r.status,1);assert.ok(json(r).failures.some(x=>x==='NONIGNORED_UNTRACKED:new.txt'));}finally{await f.cleanup();}});
test('T5 GIT_INDEX_FILE set causes failure',async()=>{const f=await repoFixture();try{const env={...process.env,GIT_INDEX_FILE:join(f.base,'other-index')};const r=run(f.repo,'preflight',expected(f),env);assert.equal(r.status,1);assert.ok(json(r).failures.includes('GIT_INDEX_FILE_SET'));}finally{await f.cleanup();}});
test('T6 index.lock exists causes failure',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'.git','index.lock'),'');const r=run(f.repo,'preflight',expected(f));assert.equal(r.status,1);assert.ok(json(r).failures.includes('INDEX_LOCK_EXISTS'));}finally{await rm(join(f.repo,'.git','index.lock'),{force:true});await f.cleanup();}});
test('T7 expected head branch and remote mismatches are specific',async()=>{const f=await repoFixture();try{const r=run(f.repo,'preflight',['--expected-head','0'.repeat(40),'--expected-branch','wrong','--expected-remote','1'.repeat(40)]);assert.equal(r.status,1);const failures=json(r).failures;assert.ok(failures.some(x=>x.startsWith('HEAD_MISMATCH:')));assert.ok(failures.some(x=>x.startsWith('BRANCH_MISMATCH:')));assert.ok(failures.some(x=>x.startsWith('REMOTE_MISMATCH:')));}finally{await f.cleanup();}});
test('T8 postcommit repairs index stat state and preserves bytes',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'base.txt'),'changed\n');git(f.repo,['add','base.txt']);git(f.repo,['commit','-m','change']);const head=git(f.repo,['rev-parse','HEAD']).stdout.trim();const parent=git(f.repo,['rev-parse','HEAD^']).stdout.trim();git(f.repo,['push','origin',`${f.branch}:${f.branch}`]);const before=sha(await readFile(join(f.repo,'base.txt')));const r=run(f.repo,'postcommit',['--expected-head',head,'--expected-parent',parent,'--expected-branch',f.branch,'--expected-remote',head,'--allow','base.txt']);assert.equal(r.status,0,r.stdout);assert.equal(json(r).realIndexSynchronized,true);assert.equal(sha(await readFile(join(f.repo,'base.txt'))),before);}finally{await f.cleanup();}});
test('T9 CRLF and LF bytes remain exact across postcommit',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'crlf.txt'),Buffer.from('a\r\nb\r\n'));await writeFile(join(f.repo,'lf.txt'),Buffer.from('a\nb\n'));git(f.repo,['add','crlf.txt','lf.txt']);git(f.repo,['commit','-m','eol']);const head=git(f.repo,['rev-parse','HEAD']).stdout.trim(),parent=git(f.repo,['rev-parse','HEAD^']).stdout.trim();git(f.repo,['push','origin',`${f.branch}:${f.branch}`]);const before=[sha(await readFile(join(f.repo,'crlf.txt'))),sha(await readFile(join(f.repo,'lf.txt')))];const r=run(f.repo,'postcommit',['--expected-head',head,'--expected-parent',parent,'--expected-branch',f.branch,'--expected-remote',head,'--allow','crlf.txt','--allow','lf.txt']);assert.equal(r.status,0,r.stdout);assert.deepEqual([sha(await readFile(join(f.repo,'crlf.txt'))),sha(await readFile(join(f.repo,'lf.txt')))],before);}finally{await f.cleanup();}});
test('T10 native path containing spaces works with shell false',async()=>{const f=await repoFixture({space:true});try{const r=run(f.repo,'preflight',expected(f));assert.equal(r.status,0,r.stderr);assert.match(json(r).repoRoot,/ /);}finally{await f.cleanup();}});
test('T11 non allowlist commit file fails postcommit specifically',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'a.txt'),'a');await writeFile(join(f.repo,'b.txt'),'b');git(f.repo,['add','a.txt','b.txt']);git(f.repo,['commit','-m','two']);const head=git(f.repo,['rev-parse','HEAD']).stdout.trim(),parent=git(f.repo,['rev-parse','HEAD^']).stdout.trim();git(f.repo,['push','origin',`${f.branch}:${f.branch}`]);const r=run(f.repo,'postcommit',['--expected-head',head,'--expected-parent',parent,'--expected-branch',f.branch,'--expected-remote',head,'--allow','a.txt']);assert.equal(r.status,1);assert.ok(json(r).failures.some(x=>x.startsWith('COMMIT_ALLOWLIST_MISMATCH:')));}finally{await f.cleanup();}});
test('T12 report is parseable and has ordered handoff fields',async()=>{const f=await repoFixture();try{const r=run(f.repo,'report');assert.equal(r.status,0,r.stderr);const o=json(r);assert.equal(o.mode,'report');assert.deepEqual(Object.keys(o.handoffHeader),['finalHEAD','gitLsRemote','checkpointName','checkpointCommit','manifestPath','manifestSha256','patchPath','patchSha256','worktree','staging','nonIgnoredUntracked','unsavedWip']);assert.equal(o.handoffHeader.checkpointName,'NOT_PROVIDED');}finally{await f.cleanup();}});
test('T13 allow-dirty accepts only exact listed files',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'base.txt'),'dirty\n');let r=run(f.repo,'preflight',[...expected(f),'--allow-dirty','base.txt']);assert.equal(r.status,0,r.stdout);await writeFile(join(f.repo,'other.txt'),'x');r=run(f.repo,'preflight',[...expected(f),'--allow-dirty','base.txt']);assert.equal(r.status,1);assert.ok(json(r).failures.includes('NONIGNORED_UNTRACKED:other.txt'));}finally{await f.cleanup();}});
test('T14 source contains no forbidden git mutation commands',async()=>{const source=await readFile(guard,'utf8');for(const word of ['reset','restore','checkout','clean','stash','rebase','commit','push'])assert.equal(new RegExp(`\\['${word}'|\\"${word}\\"`).test(source),false,word);assert.match(source,/shell: false/);});
test('T15 exact allow-dirty untracked file passes and is reported',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'new.txt'),'x');const r=run(f.repo,'preflight',[...expected(f),'--allow-dirty','new.txt']);assert.equal(r.status,0,r.stdout);const o=json(r);assert.deepEqual(o.allowlistedUntracked,['new.txt']);assert.deepEqual(o.unauthorizedUntracked,[]);}finally{await f.cleanup();}});
test('T16 outside allowlist untracked remains blocked by exact path',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'allowed.txt'),'a');await writeFile(join(f.repo,'blocked.txt'),'b');const r=run(f.repo,'preflight',[...expected(f),'--allow-dirty','allowed.txt']);assert.equal(r.status,1);const o=json(r);assert.deepEqual(o.allowlistedUntracked,['allowed.txt']);assert.deepEqual(o.unauthorizedUntracked,['blocked.txt']);assert.ok(o.failures.includes('NONIGNORED_UNTRACKED:blocked.txt'));}finally{await f.cleanup();}});
test('T17 partial untracked allowlist blocks the second file',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'one.txt'),'1');await writeFile(join(f.repo,'two.txt'),'2');const r=run(f.repo,'preflight',[...expected(f),'--allow-dirty','one.txt']);assert.equal(r.status,1);assert.ok(json(r).failures.includes('NONIGNORED_UNTRACKED:two.txt'));}finally{await f.cleanup();}});
test('T18 tracked dirty and allowlisted untracked can coexist',async()=>{const f=await repoFixture();try{await writeFile(join(f.repo,'base.txt'),'dirty\n');await writeFile(join(f.repo,'new.txt'),'new');const r=run(f.repo,'preflight',[...expected(f),'--allow-dirty','base.txt','--allow-dirty','new.txt']);assert.equal(r.status,0,r.stdout);const o=json(r);assert.deepEqual(o.allowlistedTrackedDirty,['base.txt']);assert.deepEqual(o.allowlistedUntracked,['new.txt']);assert.deepEqual(o.unauthorizedTrackedDirty,[]);assert.deepEqual(o.unauthorizedUntracked,[]);}finally{await f.cleanup();}});
test('T19 directory prefix does not authorize child',async()=>{const f=await repoFixture();try{await mkdir(join(f.repo,'scripts'));await writeFile(join(f.repo,'scripts','exec-guard.mjs'),'x');const r=run(f.repo,'preflight',[...expected(f),'--allow-dirty','scripts']);assert.equal(r.status,1);const o=json(r);assert.ok(o.failures.includes('ALLOW_DIRTY_NOT_DIRTY:scripts'));assert.ok(o.failures.includes('NONIGNORED_UNTRACKED:scripts/exec-guard.mjs'));}finally{await f.cleanup();}});
test('T20 traversal and absolute allow-dirty paths are rejected',async()=>{const f=await repoFixture();try{let r=run(f.repo,'preflight',[...expected(f),'--allow-dirty','../escape']);assert.equal(r.status,2);assert.ok(json(r).failures.includes('INVALID_REPO_RELATIVE_PATH:../escape'));const absolute=resolve(f.repo,'base.txt');r=run(f.repo,'preflight',[...expected(f),'--allow-dirty',absolute]);assert.equal(r.status,2);assert.ok(json(r).failures.some(x=>x.startsWith('INVALID_REPO_RELATIVE_PATH:')));}finally{await f.cleanup();}});
