import test from 'node:test';import assert from 'node:assert/strict';import {cp,mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,dirname,resolve} from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),validator=resolve(root,'scripts/verify-step6-legacy-run-api-contract-001.mjs');
const contractRel='verification/VERIFIED-SEMANTICS-UNIFICATION-001/step6-legacy-run-api-contract.json',reportRel='verification/VERIFIED-SEMANTICS-UNIFICATION-001/step6-execution-report.schema.json';
async function fixture(){const d=await mkdtemp(join(tmpdir(),'s6-contract-'));for(const p of ['package.json','verification/VERIFIED-SEMANTICS-UNIFICATION-001/step6-legacy-run-api-contract.schema.json',contractRel,'verification/VERIFIED-SEMANTICS-UNIFICATION-001/step6-legacy-run-api-test-audit.schema.json','verification/VERIFIED-SEMANTICS-UNIFICATION-001/step6-legacy-run-api-test-audit.template.json','verification/VERIFIED-SEMANTICS-UNIFICATION-001/step6-legacy-run-api-test-audit.template.md','verification/VERIFIED-SEMANTICS-UNIFICATION-001/step6-historical-assertions.template.md',reportRel,'verification/VERIFIED-SEMANTICS-UNIFICATION-001/step5-to-step8-authoritative-index.json','scripts/verify-memories.mjs','scripts/verify-verification-layer.mjs','scripts/verify-tasks-runs.mjs']){await mkdir(dirname(join(d,p)),{recursive:true});await cp(join(root,p),join(d,p))}return d}
function run(d,cwd=root){const args=[validator];if(d)args.push('--root',d);const r=spawnSync(process.execPath,args,{cwd,encoding:'utf8',shell:false});return{...r,json:JSON.parse(r.stdout)}}function codes(r){return r.json.failures.map(x=>x.code)}async function mutate(d,rel,fn){const p=join(d,rel),o=JSON.parse(await readFile(p,'utf8'));fn(o);await writeFile(p,JSON.stringify(o,null,2)+'\n')}
async function negative(name,code,fn){test(name,async()=>{const d=await fixture();try{await fn(d);const r=run(d);assert.notEqual(r.status,0);assert.ok(codes(r).includes(code),JSON.stringify(r.json))}finally{await rm(d,{recursive:true,force:true})}})}
test('T1 legal contract passes',async()=>{const d=await fixture();try{const r=run(d);assert.equal(r.status,0);assert.equal(r.json.ok,true)}finally{await rm(d,{recursive:true,force:true})}});
await negative('T2 DECISION-A promotion fails','DECISION_A_FIXED',d=>mutate(d,contractRel,o=>o.productDecisions['STEP6-TRUST-SEMANTICS-001']='BUSINESS_VERIFIED_PROMOTION'));
await negative('T3 DECISION-B expansion fails','DECISION_B_FIXED',d=>mutate(d,contractRel,o=>o.productDecisions['STEP6-ARCHIVE-UNIVERSE-001']='ALL_RUN_API_BEHAVIOR'));
await negative('T4 duplicate assertionId fails','ASSERTION_ID_UNIQUE',d=>mutate(d,contractRel,o=>o.archiveUniverse.entries[1].assertionId=o.archiveUniverse.entries[0].assertionId));
await negative('T5 missing client verified block fails','REQUIRED_BLOCK:S6-MEM-A001',d=>mutate(d,contractRel,o=>{o.archiveUniverse.entries=o.archiveUniverse.entries.filter(x=>x.assertionId!=='S6-MEM-A001');o.archiveUniverse.expectedCount--}));
await negative('T6 missing isolated promotion block fails','REQUIRED_BLOCK:S6-VL-A001',d=>mutate(d,contractRel,o=>{o.archiveUniverse.entries=o.archiveUniverse.entries.filter(x=>x.assertionId!=='S6-VL-A001');o.archiveUniverse.expectedCount--}));
await negative('T7 missing fail-closed block fails','REQUIRED_BLOCK:S6-VL-A002',d=>mutate(d,contractRel,o=>{o.archiveUniverse.entries=o.archiveUniverse.entries.filter(x=>x.assertionId!=='S6-VL-A002');o.archiveUniverse.expectedCount--}));
await negative('T8 Step7 file in allowlist fails','PRODUCT_ALLOWLIST_EXACT',d=>mutate(d,contractRel,o=>o.allowlists.requiredChangedFiles.push('scripts/verify-mandatory-gates-001.mjs')));
await negative('T9 production code in allowlist fails','PRODUCT_ALLOWLIST_EXACT',d=>mutate(d,contractRel,o=>o.allowlists.requiredChangedFiles.push('server.mjs')));
await negative('T10 checkpoint or topology drift fails','TOPOLOGY_EXACT',d=>mutate(d,contractRel,o=>o.checkpointTopology.topology='ONE_COMMIT'));
await negative('T11 A1-A4 path drift fails','ARTIFACT_PATHS_EXACT',d=>mutate(d,contractRel,o=>o.artifactContracts.requiredArtifacts[3]='scripts/verify-legacy-assertion-archive-completeness-001.mjs'));
await negative('T12 report schema missing safety field fails','REPORT_FIELD:pushPerformed',async d=>{await mutate(d,reportRel,o=>o.required=o.required.filter(x=>x!=='pushPerformed'))});
test('T13 validator is read-only and fixture cleans',async()=>{const d=await fixture();const before=spawnSync(process.execPath,['-e',`const fs=require('fs'),c=require('crypto'),p=${JSON.stringify(d)};function w(x){let a=[];for(const n of fs.readdirSync(x,{withFileTypes:true})){const q=x+'/'+n.name;if(n.isDirectory())a=a.concat(w(q));else a.push(q.slice(p.length+1)+':'+c.createHash('sha256').update(fs.readFileSync(q)).digest('hex'))}return a}console.log(c.createHash('sha256').update(w(p).sort().join('\\n')).digest('hex'))`],{encoding:'utf8'}).stdout.trim();const r=run(d);const after=spawnSync(process.execPath,['-e',`const fs=require('fs'),c=require('crypto'),p=${JSON.stringify(d)};function w(x){let a=[];for(const n of fs.readdirSync(x,{withFileTypes:true})){const q=x+'/'+n.name;if(n.isDirectory())a=a.concat(w(q));else a.push(q.slice(p.length+1)+':'+c.createHash('sha256').update(fs.readFileSync(q)).digest('hex'))}return a}console.log(c.createHash('sha256').update(w(p).sort().join('\\n')).digest('hex'))`],{encoding:'utf8'}).stdout.trim();assert.equal(r.status,0);assert.equal(after,before);await rm(d,{recursive:true,force:true})});
test('R1 repository-root cwd resolves script parent',()=>{const r=run(null,root);assert.equal(r.status,0);assert.equal(r.json.resolvedRepositoryRoot,root);assert.equal(r.json.rootResolutionMode,'SCRIPT_LOCATION_PARENT')});
test('R2 nested repository cwd resolves same root',()=>{const r=run(null,resolve(root,'verification/VERIFIED-SEMANTICS-UNIFICATION-001'));assert.equal(r.status,0);assert.equal(r.json.resolvedRepositoryRoot,root);assert.equal(r.json.rootResolutionMode,'SCRIPT_LOCATION_PARENT')});
test('R3 external cwd resolves same root',()=>{const r=run(null,tmpdir());assert.equal(r.status,0);assert.equal(r.json.resolvedRepositoryRoot,root);assert.equal(r.json.rootResolutionMode,'SCRIPT_LOCATION_PARENT');assert.ok(!codes(r).some(x=>x.startsWith('FILE_EXISTS:')||x==='VALIDATOR_RUNTIME'))});
test('R4 explicit fixture root wins',async()=>{const d=await fixture();try{const r=run(d,tmpdir());assert.equal(r.status,0);assert.equal(r.json.resolvedRepositoryRoot,resolve(d));assert.equal(r.json.rootResolutionMode,'EXPLICIT_ROOT')}finally{await rm(d,{recursive:true,force:true})}});
test('R5 invalid explicit parent root is rejected exactly',()=>{const bad=resolve(root,'..'),r=run(bad,tmpdir());assert.notEqual(r.status,0);assert.deepEqual(codes(r),['ROOT_RESOLUTION_INVALID']);assert.equal(r.json.resolvedRepositoryRoot,bad);assert.equal(r.json.rootResolutionMode,'EXPLICIT_ROOT')});
test('R6 cwd variation never misreports C1-C7 or ENOENT',()=>{for(const cwd of [root,resolve(root,'scripts'),tmpdir()]){const r=run(null,cwd);assert.equal(r.status,0);assert.ok(!codes(r).some(x=>x.startsWith('FILE_EXISTS:')||x==='VALIDATOR_RUNTIME'))}});
test('S1 current real C2 passes strict C1',()=>{const r=run(null,root);assert.equal(r.status,0);assert.equal(r.json.ok,true)});
for(const [name,field,expected] of [['S2 step7Boundary object rejected','step7Boundary','$.step7Boundary:TYPE_ARRAY'],['S3 step8Boundary object rejected','step8Boundary','$.step8Boundary:TYPE_ARRAY'],['S4 securityInvariants object rejected','securityInvariants','$.securityInvariants:TYPE_ARRAY'],['S5 intermediateProductState object rejected','intermediateProductState','$.intermediateProductState:TYPE_STRING']]) await negative(name,'CONTRACT_SCHEMA_VALID',d=>mutate(d,contractRel,o=>o[field]={invalid:true}));
for(const [name,field] of [['S6a step7 non-string rejected','step7Boundary'],['S6b step8 non-string rejected','step8Boundary'],['S6c invariant non-string rejected','securityInvariants']]) test(name,async()=>{const d=await fixture();try{await mutate(d,contractRel,o=>o[field].push(7));const r=run(d);assert.notEqual(r.status,0);const f=r.json.failures.find(x=>x.code==='CONTRACT_SCHEMA_VALID');assert.ok(f.detail.some(x=>x.includes(`$.${field}[`)&&x.endsWith(':TYPE_STRING')),JSON.stringify(r.json))}finally{await rm(d,{recursive:true,force:true})}});
for(const [name,field] of [['S7a empty step7 rejected','step7Boundary'],['S7b empty step8 rejected','step8Boundary'],['S7c empty invariants rejected','securityInvariants']]) test(name,async()=>{const d=await fixture();try{await mutate(d,contractRel,o=>o[field]=[]);const r=run(d);assert.notEqual(r.status,0);const f=r.json.failures.find(x=>x.code==='CONTRACT_SCHEMA_VALID');assert.ok(f.detail.includes(`$.${field}:MIN_ITEMS`),JSON.stringify(r.json))}finally{await rm(d,{recursive:true,force:true})}});
for(const [name,field] of [['S8a duplicate step7 rejected','step7Boundary'],['S8b duplicate step8 rejected','step8Boundary'],['S8c duplicate invariant rejected','securityInvariants']]) test(name,async()=>{const d=await fixture();try{await mutate(d,contractRel,o=>o[field].push(o[field][0]));const r=run(d);assert.notEqual(r.status,0);const f=r.json.failures.find(x=>x.code==='CONTRACT_SCHEMA_VALID');assert.ok(f.detail.includes(`$.${field}:UNIQUE_ITEMS`),JSON.stringify(r.json))}finally{await rm(d,{recursive:true,force:true})}});
test('S9 invalid intermediate state rejected',async()=>{const d=await fixture();try{await mutate(d,contractRel,o=>o.intermediateProductState='PRESENT_AND_VERIFIED');const r=run(d);assert.notEqual(r.status,0);const f=r.json.failures.find(x=>x.code==='CONTRACT_SCHEMA_VALID');assert.ok(f.detail.includes('$.intermediateProductState:CONST'),JSON.stringify(r.json))}finally{await rm(d,{recursive:true,force:true})}});
test('S10 legal strict types pass from external cwd and explicit fixture',async()=>{const direct=run(null,tmpdir());assert.equal(direct.status,0);const d=await fixture();try{const explicit=run(d,tmpdir());assert.equal(explicit.status,0);assert.equal(explicit.json.rootResolutionMode,'EXPLICIT_ROOT')}finally{await rm(d,{recursive:true,force:true})}});
test('S9a legal archive command registration passes',async()=>{const d=await fixture();try{const r=run(d);assert.equal(r.status,0);for(const code of ['ARCHIVE_NPM_COMMAND_IDENTITY','ARCHIVE_NPM_COMMAND_REGISTERED','ARCHIVE_NPM_EXECUTABLE_MATCH'])assert.equal(r.json.checks.find(x=>x.code===code)?.ok,true,JSON.stringify(r.json))}finally{await rm(d,{recursive:true,force:true})}});
test('S9b missing archive command registration is rejected',async()=>{const d=await fixture();try{await mutate(d,'package.json',o=>delete o.scripts['verify:step6-legacy-run-api-archive']);const r=run(d);assert.notEqual(r.status,0);assert.ok(codes(r).includes('ARCHIVE_NPM_COMMAND_REGISTERED'),JSON.stringify(r.json))}finally{await rm(d,{recursive:true,force:true})}});
test('S9c mismatched archive command executable is rejected',async()=>{const d=await fixture();try{await mutate(d,'package.json',o=>o.scripts['verify:step6-legacy-run-api-archive']='node scripts/wrong-step6-archive-validator.mjs');const r=run(d);assert.notEqual(r.status,0);assert.ok(codes(r).includes('ARCHIVE_NPM_EXECUTABLE_MATCH'),JSON.stringify(r.json))}finally{await rm(d,{recursive:true,force:true})}});
