import test from 'node:test';import assert from 'node:assert/strict';import {cp,mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {dirname,join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),validator=resolve(root,'scripts/verify-step7-mandatory-gates-contract-001.mjs'),contractRel='verification/VERIFIED-SEMANTICS-UNIFICATION-001/step7-mandatory-gates-contract.json';
const copy=['package.json','verification/VERIFIED-SEMANTICS-UNIFICATION-001/step7-mandatory-gates-contract.schema.json',contractRel,'verification/VERIFIED-SEMANTICS-UNIFICATION-001/step7-execution-report.schema.json','verification/VERIFIED-SEMANTICS-UNIFICATION-001/step5-to-step8-authoritative-index.json','scripts/verify-mandatory-gates-001.mjs','scripts/verify-run-api-verified-injection-rejection-001.mjs','scripts/verify-data-import-verified-injection-rejection-001.mjs','scripts/verify-legacy-persisted-verified-claim-fail-closed-001.mjs','scripts/verify-isolated-run-verification-not-business-verified-001.mjs','scripts/verify-server-owned-run-fact-preservation-001.mjs','scripts/verify-ui-writable-dto-001.mjs','scripts/verify-run-trust-path-rejection-baseline-001.mjs','scripts/verify-trust-field-protocol-path-matching-001.mjs','scripts/verify-workbench-context-verified-trust-boundary-001.mjs','scripts/verify-agent-context-injection-rejection-001.mjs','scripts/verify-ui-run-status-verification-separation-001.mjs','scripts/verify-verified-assignment-invariant-001.mjs','scripts/verify-memories.mjs','scripts/verify-verification-layer.mjs','scripts/verify-tasks-runs.mjs'];
async function fixture(){const d=await mkdtemp(join(tmpdir(),'s7-contract-'));for(const p of copy){await mkdir(dirname(join(d,p)),{recursive:true});await cp(join(root,p),join(d,p))}return d}function run(d,cwd=root){const r=spawnSync(process.execPath,[validator,...(d?['--root',d]:[])],{cwd,encoding:'utf8',shell:false});return{...r,json:JSON.parse(r.stdout)}}async function mutate(d,fn){const p=join(d,contractRel),o=JSON.parse(await readFile(p,'utf8'));fn(o);await writeFile(p,JSON.stringify(o,null,2)+'\n')}function codes(r){return r.json.failures.map(x=>x.code)}async function negative(name,code,fn){test(name,async()=>{const d=await fixture();try{await mutate(d,fn);const r=run(d);assert.notEqual(r.status,0);assert.ok(codes(r).includes(code),JSON.stringify(r.json))}finally{await rm(d,{recursive:true,force:true})}})}
test('T1 real amended contract passes exact 7 plus 4 equals 11',()=>{const r=run();assert.equal(r.status,0);assert.equal(r.json.ok,true);for(const code of ['BASE_PRODUCT_ALLOWLIST_EXACT_7','REPAIR_EXTENSION_COUNT_EXACT_4','REPAIR_EXTENSION_FILES_EXACT','EFFECTIVE_PRODUCT_ALLOWLIST_EXACT_11'])assert.equal(r.json.checks.find(x=>x.code===code)?.ok,true)});
for(const [n,code,fn] of [['T2 existing count fixed','GRAPH_existingMandatoryGateCount',o=>o.executionGraph.existingMandatoryGateCount=19],['T3 specialists fixed','GRAPH_specialistRequiredCount',o=>o.executionGraph.specialistRequiredCount=11],['T4 legacy fixed','GRAPH_legacyRequiredCount',o=>o.executionGraph.legacyRequiredCount=2],['T5 minimum graph fixed','GRAPH_minimumMandatoryExecutionGraphCount',o=>o.executionGraph.minimumMandatoryExecutionGraphCount=34],['T6 sequential fixed','EXECUTION_MODE',o=>o.executionGraph.executionMode='PARALLEL'],['T7 fail-fast fixed','FAILURE_MODE',o=>o.executionGraph.failureMode='CONTINUE'],['T8 base drift fails','BASE_PRODUCT_ALLOWLIST_EXACT_7',o=>o.productAllowlist.push('server.mjs')],['T9 Step8 non-promotion','NON_PROMOTION',o=>o.successState.step8='STARTED']])await negative(n,code,fn);
await negative('R1 repair count below four fails','REPAIR_EXTENSION_COUNT_EXACT_4',o=>o.approvedFailureRepairExtension.approvedFailureRepairExtensionCount=3);
await negative('R2 fifth repair fails','REPAIR_EXTENSION_COUNT_EXACT_4',o=>{o.approvedFailureRepairExtension.approvedFailureRepairExtensionCount=5;o.approvedFailureRepairExtension.approvedFailureRepairFiles.push('scripts/verify-task-execution-loop.mjs');o.approvedFailureRepairExtension.repairs.push({repairId:'R5',failureGate:'Other',failureScript:'scripts/verify-task-execution-loop.mjs',failureOrigin:'OTHER'});o.effectiveProductAllowlist.push('scripts/verify-task-execution-loop.mjs');o.effectiveProductAllowlistCount=12});
for(const [n,p] of [['R3 execution loop forbidden','scripts/verify-task-execution-loop.mjs'],['R4 specialist forbidden','scripts/verify-run-api-verified-injection-rejection-001.mjs'],['R5 legacy forbidden','scripts/verify-memories.mjs'],['R6 agent runtime forbidden','agents/agent-runtime.mjs'],['R7 adapter forbidden','agents/interpreter-adapter.mjs'],['R8 scheduler forbidden','capabilities/capability-scheduler.mjs'],['R9 worker runtime forbidden','scripts/workbench-agent-runtime.mjs'],['R10 worker ipc forbidden','scripts/feishu-worker-ipc.mjs'],['R11 supervisor forbidden','scripts/runtime-supervisor.mjs'],['R12 Step8 forbidden','verification/step8.json'],['R13 deployment forbidden','scripts/deploy-production.mjs']])await negative(n,'REPAIR_EXTENSION_FILES_EXACT',o=>{o.approvedFailureRepairExtension.approvedFailureRepairFiles[3]=p;o.approvedFailureRepairExtension.repairs[3].failureScript=p;o.effectiveProductAllowlist[10]=p});
await negative('R14 effective allowlist unknown extra fails','EFFECTIVE_PRODUCT_ALLOWLIST_EXACT_11',o=>o.effectiveProductAllowlist[10]='scripts/unknown-repair.mjs');
await negative('R15 Task Lifecycle origin drift fails','REPAIR_EXTENSION_FILES_EXACT',o=>o.approvedFailureRepairExtension.repairs[0].failureOrigin='OTHER');
await negative('R16 Cancellation origin drift fails','REPAIR_EXTENSION_FILES_EXACT',o=>o.approvedFailureRepairExtension.repairs[1].failureOrigin='OTHER');
await negative('R17 Runtime Switch origin drift fails','REPAIR_EXTENSION_FILES_EXACT',o=>o.approvedFailureRepairExtension.repairs[2].failureOrigin='OTHER');
await negative('R18 Gateway Pure Transport origin drift fails','REPAIR_EXTENSION_FILES_EXACT',o=>o.approvedFailureRepairExtension.repairs[3].failureOrigin='OTHER');
test('T10 explicit root and external cwd',async()=>{const d=await fixture();try{const r=run(d,tmpdir());assert.equal(r.status,0);assert.equal(r.json.rootResolutionMode,'EXPLICIT_ROOT')}finally{await rm(d,{recursive:true,force:true})}});test('T11 validator is read-only',async()=>{const d=await fixture();try{const p=join(d,contractRel),before=await readFile(p);const r=run(d);const after=await readFile(p);assert.equal(r.status,0);assert.deepEqual(after,before)}finally{await rm(d,{recursive:true,force:true})}});
