import fs from 'node:fs/promises';
import { createHash, randomUUID } from 'node:crypto';
import { dirname, join } from 'node:path';
import { runtimeRoot } from '../runtime-paths.mjs';

const defaultRoot = process.env.AIW_TASK_STORE_DIR || join(runtimeRoot, 'feishu-workbench-bridge', 'tasks');
const key = (id) => createHash('sha256').update(String(id || 'unknown')).digest('hex').slice(0, 40);
const locks = new Map();
async function exclusive(id, operation) {
  const previous = locks.get(id) || Promise.resolve();
  let release;
  const current = new Promise((resolve) => { release = resolve; });
  locks.set(id, current);
  await previous;
  try { return await operation(); }
  finally { release(); if (locks.get(id) === current) locks.delete(id); }
}
export const TASK_STATES = Object.freeze(['accepted','interpreting','scheduling','ready','executing','verifying','paused','completed','waiting_for_clarification','waiting_for_confirmation','capability_unavailable','failed','cancelled']);
export const TERMINAL_TASK_STATES = new Set(['completed','capability_unavailable','failed','cancelled']);
export const RUN_STATES = Object.freeze(['created','starting','running','verifying','completed','failed','cancelled','superseded']);
export const TERMINAL_RUN_STATES = new Set(['completed','failed','cancelled','superseded']);
const allowed = new Map([
  ['accepted',new Set(['interpreting','paused','cancelled','failed'])],
  ['interpreting',new Set(['scheduling','waiting_for_clarification','paused','failed','cancelled'])],
  ['waiting_for_clarification',new Set(['interpreting','paused','cancelled','failed'])],
  ['scheduling',new Set(['ready','waiting_for_confirmation','capability_unavailable','paused','failed','cancelled'])],
  ['waiting_for_confirmation',new Set(['ready','paused','cancelled','failed'])],
  ['ready',new Set(['executing','verifying','completed','paused','failed','cancelled'])],
  ['executing',new Set(['verifying','paused','failed','cancelled'])],
  ['verifying',new Set(['completed','paused','failed','cancelled'])],
  ['paused',new Set(['interpreting','scheduling','ready','executing','verifying','cancelled','failed'])],
  ['completed',new Set()],['capability_unavailable',new Set()],['failed',new Set()],['cancelled',new Set()]
]);
const runAllowed=new Map([
  ['created',new Set(['starting','failed','cancelled','superseded'])],
  ['starting',new Set(['running','failed','cancelled','superseded'])],
  ['running',new Set(['verifying','failed','cancelled','superseded'])],
  ['verifying',new Set(['completed','failed','cancelled','superseded'])],
  ['completed',new Set()],['failed',new Set()],['cancelled',new Set()],['superseded',new Set()]
]);
function now() { return Date.now(); }
function required(value,name){const text=String(value||'').trim();if(!text)throw new Error(`${name} is required`);return text;}
function taskRevision(task){return Number.isInteger(task?.taskRevision)&&task.taskRevision>=0?task.taskRevision:0;}
function normalizeTask(task){return task?{...task,taskRevision:taskRevision(task),activeRunId:task.activeRunId||null,runs:Array.isArray(task.runs)?task.runs:[]}:task;}
export class TaskStore {
  constructor(options={}){this.root=options.root||defaultRoot;this.now=options.now||now;this.newRunId=options.newRunId||(()=>randomUUID());}
  path(taskId){return join(this.root,`${key(required(taskId,'taskId'))}.json`);}
  async load(taskId){try{return normalizeTask(JSON.parse(await fs.readFile(this.path(taskId),'utf8')));}catch{return null;}}
  async findByOriginalMessageId(originalMessageId){const wanted=required(originalMessageId,'originalMessageId');return (await this.list()).find((task)=>task.originalMessageId===wanted)||null;}
  async save(task){required(task?.taskId,'taskId');const path=this.path(task.taskId);await fs.mkdir(dirname(path),{recursive:true});const tmp=`${path}.${process.pid}.${this.now()}.tmp`;await fs.writeFile(tmp,`${JSON.stringify(task,null,2)}\n`,'utf8');await fs.rename(tmp,path);return task;}
  async create(job){const taskId=required(job.taskId||job.messageId,'taskId');const originalMessageId=required(job.originalMessageId||job.messageId,'originalMessageId');const existing=await this.load(taskId);if(existing){if(existing.originalMessageId!==originalMessageId)throw new Error(`Task ${taskId} already belongs to originalMessageId ${existing.originalMessageId}`);return existing;}const byOriginal=await this.findByOriginalMessageId(originalMessageId);if(byOriginal&&byOriginal.taskId!==taskId)throw new Error(`originalMessageId ${originalMessageId} already belongs to task ${byOriginal.taskId}`);const at=this.now();const task={taskId,originalMessageId,conversationId:required(job.conversationId||job.chatId,'conversationId'),parentTaskId:String(job.parentTaskId||''),taskRevision:0,activeRunId:null,runs:[],interpretation:null,schedulerAssignment:null,providerExecution:null,verification:null,finalResult:null,failure:null,currentState:'accepted',stateReason:'message_accepted',waitingFor:null,cancelledByUser:false,evidence:[{type:'accepted',messageId:originalMessageId,at}],createdAt:at,updatedAt:at,terminalAt:null,stateHistory:[{from:null,to:'accepted',reason:'message_accepted',actor:'gateway',evidence:{messageId:originalMessageId},timestamp:at}]};return this.save(task);}
  async patch(taskId,patch){return exclusive(`${this.root}:${taskId}`,async()=>{const task=await this.load(taskId);if(!task)throw new Error(`Task not found: ${taskId}`);for(const forbidden of ['currentState','stateReason','terminalAt','stateHistory','taskRevision','activeRunId','runs'])if(Object.hasOwn(patch,forbidden))throw new Error(`Task protected field requires dedicated operation: ${forbidden}`);if(Object.hasOwn(patch,'originalMessageId')&&patch.originalMessageId!==task.originalMessageId)throw new Error('originalMessageId is immutable');return this.save({...task,...patch,taskId,originalMessageId:task.originalMessageId,taskRevision:task.activeRunId?task.taskRevision:task.taskRevision+1,updatedAt:this.now()});});}
  async startRun(taskId,{expectedTaskRevision,leaseOwner,providerId}={}){return exclusive(`${this.root}:${taskId}`,async()=>{const task=await this.load(taskId);if(!task)throw new Error(`Task not found: ${taskId}`);if(TERMINAL_TASK_STATES.has(task.currentState))throw new Error(`Cannot start Run for terminal Task: ${task.currentState}`);if(!Number.isInteger(expectedTaskRevision)||expectedTaskRevision<0)throw new Error('expectedTaskRevision is required');if(task.taskRevision!==expectedTaskRevision)throw new Error(`Task revision conflict: expected ${expectedTaskRevision}, actual ${task.taskRevision}`);const active=task.activeRunId?task.runs.find((run)=>run.runId===task.activeRunId):null;if(active&&!TERMINAL_RUN_STATES.has(active.status))throw new Error(`Task already has active Run: ${active.runId}`);const at=this.now();const nextRevision=task.taskRevision+1;const runId=required(this.newRunId(),'runId');const attempt=Math.max(0,...task.runs.map((run)=>Number(run.attempt)||0))+1;const run={runId,taskId:task.taskId,originalMessageId:task.originalMessageId,attempt,leaseOwner:required(leaseOwner,'leaseOwner'),providerId:required(providerId,'providerId'),taskRevision:nextRevision,status:'created',createdAt:at,startedAt:null,heartbeatAt:at,finishedAt:null,progress:[],verification:null,finalEvidence:null,failureReason:null,supersededByRunId:null};const next={...task,taskRevision:nextRevision,activeRunId:runId,runs:[...task.runs,run],updatedAt:at,evidence:[...(task.evidence||[]),{type:'run_started',runId,attempt,taskRevision:nextRevision,leaseOwner:run.leaseOwner,providerId:run.providerId,at}]};return this.save(next);});}
  async supersedeAndStartRun(taskId,{expectedTaskRevision,leaseOwner,providerId}={}){return exclusive(`${this.root}:${taskId}`,async()=>{const task=await this.load(taskId);if(!task)throw new Error(`Task not found: ${taskId}`);if(task.taskRevision!==expectedTaskRevision)throw new Error(`Task revision conflict: expected ${expectedTaskRevision}, actual ${task.taskRevision}`);if(TERMINAL_TASK_STATES.has(task.currentState))throw new Error(`Cannot take over terminal Task: ${task.currentState}`);const old=task.activeRunId?task.runs.find((run)=>run.runId===task.activeRunId):null;if(!old||TERMINAL_RUN_STATES.has(old.status))throw new Error('No active Run to take over');const at=this.now();const nextRevision=task.taskRevision+1;const runId=required(this.newRunId(),'runId');const attempt=Math.max(...task.runs.map((run)=>Number(run.attempt)||0))+1;const runs=task.runs.map((run)=>run.runId===old.runId?{...run,status:'superseded',finishedAt:at,heartbeatAt:at,supersededByRunId:runId}:run);runs.push({runId,taskId:task.taskId,originalMessageId:task.originalMessageId,attempt,leaseOwner:required(leaseOwner,'leaseOwner'),providerId:required(providerId,'providerId'),taskRevision:nextRevision,status:'created',createdAt:at,startedAt:null,heartbeatAt:at,finishedAt:null,progress:[],verification:null,finalEvidence:null,failureReason:null,supersededByRunId:null});return this.save({...task,taskRevision:nextRevision,activeRunId:runId,runs,updatedAt:at,evidence:[...(task.evidence||[]),{type:'run_takeover',oldRunId:old.runId,runId,attempt,taskRevision:nextRevision,at}]});});}
  async cancelTaskWithRun(taskId,{reason='user_cancelled',actor='user',evidence={}}={}){return exclusive(`${this.root}:${taskId}`,async()=>{const task=await this.load(taskId);if(!task)throw new Error(`Task not found: ${taskId}`);if(TERMINAL_TASK_STATES.has(task.currentState))return task;if(!allowed.get(task.currentState)?.has('cancelled'))throw new Error(`Illegal task transition: ${task.currentState} -> cancelled`);const at=this.now();const runs=task.runs.map((run)=>run.runId===task.activeRunId&&!TERMINAL_RUN_STATES.has(run.status)?{...run,status:'cancelled',heartbeatAt:at,finishedAt:at,failureReason:reason}:run);return this.save({...task,activeRunId:null,runs,cancelledByUser:true,currentState:'cancelled',stateReason:reason,terminalAt:at,updatedAt:at,stateHistory:[...(task.stateHistory||[]),{from:task.currentState,to:'cancelled',reason,actor,evidence,timestamp:at}],evidence:[...(task.evidence||[]),{type:'task_cancelled',runId:task.activeRunId,reason,actor,evidence,at}]});});}
  async transitionRun(taskId,{runId,taskRevision,from,to,evidence=null}={}){return exclusive(`${this.root}:${taskId}`,async()=>{const task=await this.load(taskId);if(!task)throw new Error(`Task not found: ${taskId}`);if(task.activeRunId!==runId)throw new Error(`Stale Run: ${runId}`);if(task.taskRevision!==taskRevision)throw new Error(`Task revision conflict: expected ${taskRevision}, actual ${task.taskRevision}`);const index=task.runs.findIndex((run)=>run.runId===runId);if(index<0)throw new Error(`Run not found: ${runId}`);const run=task.runs[index];if(run.taskRevision!==taskRevision)throw new Error(`Run revision conflict: expected ${taskRevision}, actual ${run.taskRevision}`);if(run.status!==from)throw new Error(`Run state conflict: expected ${from}, actual ${run.status}`);if(!RUN_STATES.includes(to)||!runAllowed.get(from)?.has(to))throw new Error(`Illegal Run transition: ${from} -> ${to}`);const at=this.now();const updated={...run,status:to,startedAt:to==='starting'&&!run.startedAt?at:run.startedAt,heartbeatAt:at,finishedAt:TERMINAL_RUN_STATES.has(to)?at:null,...(evidence?{providerEvidence:evidence}:{})};const runs=[...task.runs];runs[index]=updated;const next={...task,runs,updatedAt:at,evidence:[...(task.evidence||[]),{type:'run_transition',runId,from,to,taskRevision,at,evidence}]};return this.save(next);});}
  async appendRunProgress(taskId,identity,progress){return this.updateActiveRun(taskId,identity,(run,at)=>({...run,heartbeatAt:at,progress:[...(run.progress||[]),progress]}),'run_progress');}
  async bindRunVerification(taskId,identity,verification){return this.updateActiveRun(taskId,identity,(run,at)=>({...run,status:'verifying',heartbeatAt:at,verification}),'run_verification');}
  async failRunVerification(taskId,identity,verification){return exclusive(`${this.root}:${taskId}`,async()=>{const task=await this.load(taskId);const run=this.assertActiveRun(task,identity);const at=this.now();const failureReason=String(verification?.failureReason||'verification_failed');const runs=task.runs.map((item)=>item.runId===run.runId?{...item,status:'failed',heartbeatAt:at,finishedAt:at,verification:{...verification,passed:false},failureReason}:item);return this.save({...task,activeRunId:null,runs,updatedAt:at,evidence:[...(task.evidence||[]),{type:'run_verification_failed',...identity,at,failureReason}]});});}
  async finalizeRun(taskId,identity,{taskState='completed',finalResult,finalEvidence}={}){return exclusive(`${this.root}:${taskId}`,async()=>{const task=await this.load(taskId);const run=this.assertActiveRun(task,identity);if(run.finalEvidence||TERMINAL_RUN_STATES.has(run.status))throw new Error(`Run Final already committed: ${run.runId}`);if(!['running','verifying'].includes(run.status))throw new Error(`Run cannot finalize from ${run.status}`);if(!allowed.get(task.currentState)?.has(taskState))throw new Error(`Illegal task transition: ${task.currentState} -> ${taskState}`);const at=this.now();const runs=task.runs.map((item)=>item.runId===run.runId?{...item,status:'completed',heartbeatAt:at,finishedAt:at,finalEvidence}:item);const next={...task,activeRunId:null,runs,finalResult,currentState:taskState,stateReason:'run_final_committed',terminalAt:at,updatedAt:at,stateHistory:[...(task.stateHistory||[]),{from:task.currentState,to:taskState,reason:'run_final_committed',actor:'agent-runtime',evidence:{...identity},timestamp:at}],evidence:[...(task.evidence||[]),{type:'run_final',...identity,at,finalEvidence}]};return this.save(next);});}
  assertActiveRun(task,{runId,taskRevision}={}){if(!task)throw new Error('Task not found');if(task.activeRunId!==runId)throw new Error(`Stale Run: ${runId}`);if(task.taskRevision!==taskRevision)throw new Error(`Task revision conflict: expected ${taskRevision}, actual ${task.taskRevision}`);const run=task.runs.find((item)=>item.runId===runId);if(!run||run.taskRevision!==taskRevision)throw new Error(`Run identity conflict: ${runId}`);return run;}
  async updateActiveRun(taskId,identity,update,type){return exclusive(`${this.root}:${taskId}`,async()=>{const task=await this.load(taskId);const run=this.assertActiveRun(task,identity);if(TERMINAL_RUN_STATES.has(run.status))throw new Error(`Run is terminal: ${run.status}`);const at=this.now();const runs=task.runs.map((item)=>item.runId===run.runId?update(item,at):item);return this.save({...task,runs,updatedAt:at,evidence:[...(task.evidence||[]),{type,...identity,at}]});});}
  async transitionTask(taskId,from,to,reason,actor,evidence){return exclusive(`${this.root}:${taskId}`,async()=>{const task=await this.load(taskId);if(!task)throw new Error(`Task not found: ${taskId}`);if(task.currentState!==from)throw new Error(`Task state conflict: expected ${from}, actual ${task.currentState}`);if(!TASK_STATES.includes(to)||!allowed.get(from)?.has(to))throw new Error(`Illegal task transition: ${from} -> ${to}`);required(reason,'reason');required(actor,'actor');if(evidence===undefined||evidence===null)throw new Error('transition evidence is required');const at=this.now();const nextRevision=task.activeRunId?task.taskRevision:task.taskRevision+1;const next={...task,taskRevision:nextRevision,currentState:to,stateReason:reason,updatedAt:at,terminalAt:TERMINAL_TASK_STATES.has(to)?at:null,stateHistory:[...(task.stateHistory||[]),{from,to,reason,actor,evidence,timestamp:at}],evidence:[...(task.evidence||[]),{type:'state_transition',from,to,reason,actor,evidence,at}]};return this.save(next);});}
  async list(){await fs.mkdir(this.root,{recursive:true});const out=[];for(const name of(await fs.readdir(this.root)).filter(x=>x.endsWith('.json'))){try{out.push(normalizeTask(JSON.parse(await fs.readFile(join(this.root,name),'utf8'))));}catch{}}return out;}
  async listConversation(conversationId){return (await this.list()).filter(x=>x.conversationId===conversationId).sort((a,b)=>a.createdAt-b.createdAt);}
  async latestNonTerminal(conversationId){const items=(await this.listConversation(conversationId)).filter(x=>!TERMINAL_TASK_STATES.has(x.currentState));return items.at(-1)||null;}
}
export async function transitionTask(store,taskId,from,to,reason,actor,evidence){return store.transitionTask(taskId,from,to,reason,actor,evidence);}
